config/routes.rb
Jeeque::Application.routes.draw do
  resources :subtopiccodes

  resources :topiccodes

  resources :scodes

  get "random/oneques"
  get "random/quespaper"
  get "random/chingy"
  resources :questions
  resources :random
  root 'random#index'

  

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :opa, :opb, :opc, :opd, :ro, :year, :examcode, :subjectcode, :topiccode, :stopiccode)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :opa %><br>
    <%= f.text_area :opa %>
  </div>
  <div class="field">
    <%= f.label :opb %><br>
    <%= f.text_area :opb %>
  </div>
  <div class="field">
    <%= f.label :opc %><br>
    <%= f.text_area :opc %>
  </div>
  <div class="field">
    <%= f.label :opd %><br>
    <%= f.text_area :opd %>
  </div>
  <div class="field">
    <%= f.label :ro %><br>
    <%= f.text_field :ro %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.date_select :year %>
  </div>
  <div class="field">
    <%= f.label :examcode %><br>
    <%= f.number_field :examcode %>
  </div>
  <div class="field">
    <%= f.label :subjectcode %><br>
    <%= f.number_field :subjectcode %>
  </div>
  <div class="field">
    <%= f.label :topiccode %><br>
    <%= f.number_field :topiccode %>
  </div>
  <div class="field">
    <%= f.label :stopiccode %><br>
    <%= f.number_field :stopiccode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Opa</th>
      <th>Opb</th>
      <th>Opc</th>
      <th>Opd</th>
      <th>Ro</th>
      <th>Year</th>
      <th>Examcode</th>
      <th>Subjectcode</th>
      <th>Topiccode</th>
      <th>Stopiccode</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question.html_safe %></td>
        <td><%= question.opa %></td>
        <td><%= question.opb %></td>
        <td><%= question.opc %></td>
        <td><%= question.opd %></td>
        <td><%= question.ro %></td>
        <td><%= question.year %></td>
        <td><%= question.examcode %></td>
        <td><%= question.subjectcode %></td>
        <td><%= question.topiccode %></td>
        <td><%= question.stopiccode %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>
<%= link_to 'Random Question Generator', random_index_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Opa:</strong>
  <%= @question.opa %>
</p>

<p>
  <strong>Opb:</strong>
  <%= @question.opb %>
</p>

<p>
  <strong>Opc:</strong>
  <%= @question.opc %>
</p>

<p>
  <strong>Opd:</strong>
  <%= @question.opd %>
</p>

<p>
  <strong>Ro:</strong>
  <%= @question.ro %>
</p>

<p>
  <strong>Year:</strong>
  <%= @question.year %>
</p>

<p>
  <strong>Examcode:</strong>
  <%= @question.examcode %>
</p>

<p>
  <strong>Subjectcode:</strong>
  <%= @question.subjectcode %>
</p>

<p>
  <strong>Topiccode:</strong>
  <%= @question.topiccode %>
</p>

<p>
  <strong>Stopiccode:</strong>
  <%= @question.stopiccode %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>