config/routes.rb
Jeeque::Application.routes.draw do
  resources :subtopiccodes

  resources :topiccodes

  resources :scodes

  get "random/oneques"
  get "random/quespaper"
  get "random/chingy"
  resources :questions
  resources :random
  root 'random#index'

  

end

app/models/subtopiccode.rb
class Subtopiccode < ActiveRecord::Base
	belongs_to :topiccode
end

app/controllers/subtopiccodes_controller.rb
class SubtopiccodesController < ApplicationController
  before_action :set_subtopiccode, only: [:show, :edit, :update, :destroy]

  # GET /subtopiccodes
  # GET /subtopiccodes.json
  def index
    @subtopiccodes = Subtopiccode.all
  end

  # GET /subtopiccodes/1
  # GET /subtopiccodes/1.json
  def show
  end

  # GET /subtopiccodes/new
  def new
    @subtopiccode = Subtopiccode.new
  end

  # GET /subtopiccodes/1/edit
  def edit
  end

  # POST /subtopiccodes
  # POST /subtopiccodes.json
  def create
    @subtopiccode = Subtopiccode.new(subtopiccode_params)

    respond_to do |format|
      if @subtopiccode.save
        format.html { redirect_to @subtopiccode, notice: 'Subtopiccode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subtopiccode }
      else
        format.html { render action: 'new' }
        format.json { render json: @subtopiccode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtopiccodes/1
  # PATCH/PUT /subtopiccodes/1.json
  def update
    respond_to do |format|
      if @subtopiccode.update(subtopiccode_params)
        format.html { redirect_to @subtopiccode, notice: 'Subtopiccode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subtopiccode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtopiccodes/1
  # DELETE /subtopiccodes/1.json
  def destroy
    @subtopiccode.destroy
    respond_to do |format|
      format.html { redirect_to subtopiccodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtopiccode
      @subtopiccode = Subtopiccode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subtopiccode_params
      params.require(:subtopiccode).permit(:stcode, :stname, :tcode, :active)
    end
end

app/helpers/subtopiccodes_helper.rb
module SubtopiccodesHelper
end

app/views/subtopiccodes/_form.html.erb
<%= form_for(@subtopiccode) do |f| %>
  <% if @subtopiccode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subtopiccode.errors.count, "error") %> prohibited this subtopiccode from being saved:</h2>

      <ul>
      <% @subtopiccode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stcode %><br>
    <%= f.number_field :stcode %>
  </div>
  <div class="field">
    <%= f.label :stname %><br>
    <%= f.text_field :stname %>
  </div>
  <div class="field">
    <%= f.label :tcode %><br>
    <%= f.number_field :tcode %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.text_field :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subtopiccodes/edit.html.erb
<h1>Editing subtopiccode</h1>

<%= render 'form' %>

<%= link_to 'Show', @subtopiccode %> |
<%= link_to 'Back', subtopiccodes_path %>

app/views/subtopiccodes/index.html.erb
<h1>Listing subtopiccodes</h1>

<table>
  <thead>
    <tr>
      <th>Stcode</th>
      <th>Stname</th>
      <th>Tcode</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subtopiccodes.each do |subtopiccode| %>
      <tr>
        <td><%= subtopiccode.stcode %></td>
        <td><%= subtopiccode.stname %></td>
        <td><%= subtopiccode.tcode %></td>
        <td><%= subtopiccode.active %></td>
        <td><%= link_to 'Show', subtopiccode %></td>
        <td><%= link_to 'Edit', edit_subtopiccode_path(subtopiccode) %></td>
        <td><%= link_to 'Destroy', subtopiccode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subtopiccode', new_subtopiccode_path %>

app/views/subtopiccodes/new.html.erb
<h1>New subtopiccode</h1>

<%= render 'form' %>

<%= link_to 'Back', subtopiccodes_path %>

app/views/subtopiccodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stcode:</strong>
  <%= @subtopiccode.stcode %>
</p>

<p>
  <strong>Stname:</strong>
  <%= @subtopiccode.stname %>
</p>

<p>
  <strong>Tcode:</strong>
  <%= @subtopiccode.tcode %>
</p>

<p>
  <strong>Active:</strong>
  <%= @subtopiccode.active %>
</p>

<%= link_to 'Edit', edit_subtopiccode_path(@subtopiccode) %> |
<%= link_to 'Back', subtopiccodes_path %>