config/routes.rb
Jeeque::Application.routes.draw do
  resources :subtopiccodes

  resources :topiccodes

  resources :scodes

  get "random/oneques"
  get "random/quespaper"
  get "random/chingy"
  resources :questions
  resources :random
  root 'random#index'

  

end

app/models/topiccode.rb
class Topiccode < ActiveRecord::Base
	belongs_to :scode
end

app/controllers/topiccodes_controller.rb
class TopiccodesController < ApplicationController
  before_action :set_topiccode, only: [:show, :edit, :update, :destroy]

  # GET /topiccodes
  # GET /topiccodes.json
  def index
    @topiccodes = Topiccode.all
  end

  # GET /topiccodes/1
  # GET /topiccodes/1.json
  def show
  end

  # GET /topiccodes/new
  def new
    @topiccode = Topiccode.new
  end

  # GET /topiccodes/1/edit
  def edit
  end

  # POST /topiccodes
  # POST /topiccodes.json
  def create
    @topiccode = Topiccode.new(topiccode_params)

    respond_to do |format|
      if @topiccode.save
        format.html { redirect_to @topiccode, notice: 'Topiccode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topiccode }
      else
        format.html { render action: 'new' }
        format.json { render json: @topiccode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topiccodes/1
  # PATCH/PUT /topiccodes/1.json
  def update
    respond_to do |format|
      if @topiccode.update(topiccode_params)
        format.html { redirect_to @topiccode, notice: 'Topiccode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topiccode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topiccodes/1
  # DELETE /topiccodes/1.json
  def destroy
    @topiccode.destroy
    respond_to do |format|
      format.html { redirect_to topiccodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topiccode
      @topiccode = Topiccode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topiccode_params
      params.require(:topiccode).permit(:tcode, :tname, :scode, :active)
    end
end

app/helpers/topiccodes_helper.rb
module TopiccodesHelper
end

app/views/topiccodes/_form.html.erb
<%= form_for(@topiccode) do |f| %>
  <% if @topiccode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topiccode.errors.count, "error") %> prohibited this topiccode from being saved:</h2>

      <ul>
      <% @topiccode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tcode %><br>
    <%= f.number_field :tcode %>
  </div>
  <div class="field">
    <%= f.label :tname %><br>
    <%= f.text_field :tname %>
  </div>
  <div class="field">
    <%= f.label :scode %><br>
    <%= f.number_field :scode %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.text_field :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topiccodes/edit.html.erb
<h1>Editing topiccode</h1>

<%= render 'form' %>

<%= link_to 'Show', @topiccode %> |
<%= link_to 'Back', topiccodes_path %>

app/views/topiccodes/index.html.erb
<h1>Listing topiccodes</h1>

<table>
  <thead>
    <tr>
      <th>Tcode</th>
      <th>Tname</th>
      <th>Scode</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topiccodes.each do |topiccode| %>
      <tr>
        <td><%= topiccode.tcode %></td>
        <td><%= topiccode.tname %></td>
        <td><%= topiccode.scode %></td>
        <td><%= topiccode.active %></td>
        <td><%= link_to 'Show', topiccode %></td>
        <td><%= link_to 'Edit', edit_topiccode_path(topiccode) %></td>
        <td><%= link_to 'Destroy', topiccode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topiccode', new_topiccode_path %>

app/views/topiccodes/new.html.erb
<h1>New topiccode</h1>

<%= render 'form' %>

<%= link_to 'Back', topiccodes_path %>

app/views/topiccodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tcode:</strong>
  <%= @topiccode.tcode %>
</p>

<p>
  <strong>Tname:</strong>
  <%= @topiccode.tname %>
</p>

<p>
  <strong>Scode:</strong>
  <%= @topiccode.scode %>
</p>

<p>
  <strong>Active:</strong>
  <%= @topiccode.active %>
</p>

<%= link_to 'Edit', edit_topiccode_path(@topiccode) %> |
<%= link_to 'Back', topiccodes_path %>