config/routes.rb
Jeeque::Application.routes.draw do
  resources :subtopiccodes

  resources :topiccodes

  resources :scodes

  get "random/oneques"
  get "random/quespaper"
  get "random/chingy"
  resources :questions
  resources :random
  root 'random#index'

  

end

app/models/scode.rb
class Scode < ActiveRecord::Base
end

app/controllers/scodes_controller.rb
class ScodesController < ApplicationController
  before_action :set_scode, only: [:show, :edit, :update, :destroy]

  # GET /scodes
  # GET /scodes.json
  def index
    @scodes = Scode.all
  end

  # GET /scodes/1
  # GET /scodes/1.json
  def show
  end

  # GET /scodes/new
  def new
    @scode = Scode.new
  end

  # GET /scodes/1/edit
  def edit
  end

  # POST /scodes
  # POST /scodes.json
  def create
    @scode = Scode.new(scode_params)

    respond_to do |format|
      if @scode.save
        format.html { redirect_to @scode, notice: 'Scode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scode }
      else
        format.html { render action: 'new' }
        format.json { render json: @scode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scodes/1
  # PATCH/PUT /scodes/1.json
  def update
    respond_to do |format|
      if @scode.update(scode_params)
        format.html { redirect_to @scode, notice: 'Scode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scodes/1
  # DELETE /scodes/1.json
  def destroy
    @scode.destroy
    respond_to do |format|
      format.html { redirect_to scodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scode
      @scode = Scode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scode_params
      params.require(:scode).permit(:scode, :sname)
    end
end

app/helpers/scodes_helper.rb
module ScodesHelper
end

app/views/scodes/_form.html.erb
<%= form_for(@scode) do |f| %>
  <% if @scode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scode.errors.count, "error") %> prohibited this scode from being saved:</h2>

      <ul>
      <% @scode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scode %><br>
    <%= f.text_field :scode %>
  </div>
  <div class="field">
    <%= f.label :sname %><br>
    <%= f.text_field :sname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scodes/edit.html.erb
<h1>Editing scode</h1>

<%= render 'form' %>

<%= link_to 'Show', @scode %> |
<%= link_to 'Back', scodes_path %>

app/views/scodes/index.html.erb
<h1>Listing scodes</h1>

<table>
  <thead>
    <tr>
      <th>Scode</th>
      <th>Sname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scodes.each do |scode| %>
      <tr>
        <td><%= scode.scode %></td>
        <td><%= scode.sname %></td>
        <td><%= link_to 'Show', scode %></td>
        <td><%= link_to 'Edit', edit_scode_path(scode) %></td>
        <td><%= link_to 'Destroy', scode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scode', new_scode_path %>

app/views/scodes/new.html.erb
<h1>New scode</h1>

<%= render 'form' %>

<%= link_to 'Back', scodes_path %>

app/views/scodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scode:</strong>
  <%= @scode.scode %>
</p>

<p>
  <strong>Sname:</strong>
  <%= @scode.sname %>
</p>

<%= link_to 'Edit', edit_scode_path(@scode) %> |
<%= link_to 'Back', scodes_path %>